// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : /usr/share/plasma-wayland-protocols/plasma-shell.xml
//
// plasma_shell Protocol Copyright:
//
// SPDX-FileCopyrightText: 2013-2014 Pier Luigi Fiorini
//
// SPDX-License-Identifier: LGPL-2.1-or-later

package plasmashell

import "github.com/rajveermalviya/go-wayland/wayland/client"

// OrgKdePlasmaShell : create shell windows and helpers
//
// This interface is used by KF5 powered Wayland shells to communicate with
// the compositor and can only be bound one time.
type OrgKdePlasmaShell struct {
	client.BaseProxy
}

// NewOrgKdePlasmaShell : create shell windows and helpers
//
// This interface is used by KF5 powered Wayland shells to communicate with
// the compositor and can only be bound one time.
func NewOrgKdePlasmaShell(ctx *client.Context) *OrgKdePlasmaShell {
	orgKdePlasmaShell := &OrgKdePlasmaShell{}
	ctx.Register(orgKdePlasmaShell)
	return orgKdePlasmaShell
}

// GetSurface : create a shell surface from a surface
//
// Create a shell surface for an existing surface.
//
// Only one shell surface can be associated with a given
// surface.
func (i *OrgKdePlasmaShell) GetSurface(surface *client.Surface) (*OrgKdePlasmaSurface, error) {
	id := NewOrgKdePlasmaSurface(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], id.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], surface.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return id, err
}

func (i *OrgKdePlasmaShell) Destroy() error {
	i.Context().Unregister(i)
	return nil
}

// OrgKdePlasmaSurface : metadata interface
//
// An interface that may be implemented by a wl_surface, for
// implementations that provide the shell user interface.
//
// It provides requests to set surface roles, assign an output
// or set the position in output coordinates.
//
// On the server side the object is automatically destroyed when
// the related wl_surface is destroyed.  On client side,
// org_kde_plasma_surface.destroy() must be called before
// destroying the wl_surface object.
type OrgKdePlasmaSurface struct {
	client.BaseProxy
	autoHiddenPanelHiddenHandler OrgKdePlasmaSurfaceAutoHiddenPanelHiddenHandlerFunc
	autoHiddenPanelShownHandler  OrgKdePlasmaSurfaceAutoHiddenPanelShownHandlerFunc
}

// NewOrgKdePlasmaSurface : metadata interface
//
// An interface that may be implemented by a wl_surface, for
// implementations that provide the shell user interface.
//
// It provides requests to set surface roles, assign an output
// or set the position in output coordinates.
//
// On the server side the object is automatically destroyed when
// the related wl_surface is destroyed.  On client side,
// org_kde_plasma_surface.destroy() must be called before
// destroying the wl_surface object.
func NewOrgKdePlasmaSurface(ctx *client.Context) *OrgKdePlasmaSurface {
	orgKdePlasmaSurface := &OrgKdePlasmaSurface{}
	ctx.Register(orgKdePlasmaSurface)
	return orgKdePlasmaSurface
}

// Destroy : remove org_kde_plasma_surface interface
//
// The org_kde_plasma_surface interface is removed from the
// wl_surface object that was turned into a shell surface with the
// org_kde_plasma_shell.get_surface request.
// The shell surface role is lost and wl_surface is unmapped.
func (i *OrgKdePlasmaSurface) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetOutput : assign an output to this shell surface
//
// Assign an output to this shell surface.
// The compositor will use this information to set the position
// when org_kde_plasma_surface.set_position request is
// called.
func (i *OrgKdePlasmaSurface) SetOutput(output *client.Output) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], output.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPosition : change the shell surface position
//
// Move the surface to new coordinates.
//
// Coordinates are global, for example 50,50 for a 1920,0+1920x1080 output
// is 1970,50 in global coordinates space.
//
// Use org_kde_plasma_surface.set_output to assign an output
// to this surface.
//
//	x: x coordinate in global space
//	y: y coordinate in global space
func (i *OrgKdePlasmaSurface) SetPosition(x, y int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetRole : assign a role to this surface
//
// Assign a role to a shell surface.
//
// The compositor handles surfaces depending on their role.
// See the explanation below.
//
// This request fails if the surface already has a role, this means
// the surface role may be assigned only once.
//
// == Surfaces with splash role ==
//
// Splash surfaces are placed above every other surface during the
// shell startup phase.
//
// The surfaces are placed according to the output coordinates.
// No size is imposed to those surfaces, the shell has to resize
// them according to output size.
//
// These surfaces are meant to hide the desktop during the startup
// phase so that the user will always see a ready to work desktop.
//
// A shell might not create splash surfaces if the compositor reveals
// the desktop in an alternative fashion, for example with a fade
// in effect.
//
// That depends on how much time the desktop usually need to prepare
// the workspace or specific design decisions.
// This specification doesn't impose any particular design.
//
// When the startup phase is finished, the shell will send the
// org_kde_plasma.desktop_ready request to the compositor.
//
// == Surfaces with desktop role ==
//
// Desktop surfaces are placed below all other surfaces and are used
// to show the actual desktop view with icons, search results or
// controls the user will interact with. What to show depends on the
// shell implementation.
//
// The surfaces are placed according to the output coordinates.
// No size is imposed to those surfaces, the shell has to resize
// them according to output size.
//
// Only one surface per output can have the desktop role.
//
// == Surfaces with dashboard role ==
//
// Dashboard surfaces are placed above desktop surfaces and are used to
// show additional widgets and controls.
//
// The surfaces are placed according to the output coordinates.
// No size is imposed to those surfaces, the shell has to resize
// them according to output size.
//
// Only one surface per output can have the dashboard role.
//
// == Surfaces with config role ==
//
// A configuration surface is shown when the user wants to configure
// panel or desktop views.
//
// Only one surface per output can have the config role.
//
// TODO: This should grab the input like popup menus, right?
//
// == Surfaces with overlay role ==
//
// Overlays are special surfaces that shows for a limited amount
// of time.  Such surfaces are useful to display things like volume,
// brightness and status changes.
//
// Compositors may decide to show those surfaces in a layer above
// all surfaces, even full screen ones if so is desired.
//
// == Surfaces with notification role ==
//
// Notification surfaces display informative content for a limited
// amount of time.  The compositor may decide to show them in a corner
// depending on the configuration.
//
// These surfaces are shown in a layer above all other surfaces except
// for full screen ones.
//
// == Surfaces with lock role ==
//
// The lock surface is shown by the compositor when the session is
// locked, users interact with it to unlock the session.
//
// Compositors should move lock surfaces to 0,0 in output
// coordinates space and hide all other surfaces for security sake.
// For the same reason it is recommended that clients make the
// lock surface as big as the screen.
//
// Only one surface per output can have the lock role.
func (i *OrgKdePlasmaSurface) SetRole(role uint32) error {
	const opcode = 3
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(role))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPanelBehavior : set or unset the panel
//
// Set flags bitmask as described by the flag enum.
// Pass 0 to unset any flag, the surface will adjust its behavior to
// the default.
//
//	flag: panel_behavior enum value
func (i *OrgKdePlasmaSurface) SetPanelBehavior(flag uint32) error {
	const opcode = 4
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(flag))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSkipTaskbar : make the window skip the taskbar
//
// Setting this bit to the window, will make it say it prefers to not be listed in the taskbar. Taskbar implementations may or may not follow this hint.
//
//	skip: Boolean value that sets whether to skip the taskbar
func (i *OrgKdePlasmaSurface) SetSkipTaskbar(skip uint32) error {
	const opcode = 5
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(skip))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// PanelAutoHideHide : Hide the auto-hiding panel
//
// A panel surface with panel_behavior auto_hide can perform this request to hide the panel
// on a screen edge without unmapping it. The compositor informs the client about the panel
// being hidden with the event auto_hidden_panel_hidden.
//
// The compositor will restore the visibility state of the
// surface when the pointer touches the screen edge the panel borders. Once the compositor restores
// the visibility the event auto_hidden_panel_shown will be sent. This event will also be sent
// if the compositor is unable to hide the panel.
//
// The client can also request to show the panel again with the request panel_auto_hide_show.
func (i *OrgKdePlasmaSurface) PanelAutoHideHide() error {
	const opcode = 6
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// PanelAutoHideShow : Show the auto-hiding panel
//
// A panel surface with panel_behavior auto_hide can perform this request to show the panel
// again which got hidden with panel_auto_hide_hide.
func (i *OrgKdePlasmaSurface) PanelAutoHideShow() error {
	const opcode = 7
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetPanelTakesFocus : Whether a panel takes focus
//
// By default various org_kde_plasma_surface roles do not take focus and cannot be
// activated. With this request the compositor can be instructed to pass focus also to this
// org_kde_plasma_surface.
//
//	takesFocus: Boolean value that sets whether the panel takes focus
func (i *OrgKdePlasmaSurface) SetPanelTakesFocus(takesFocus uint32) error {
	const opcode = 8
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(takesFocus))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// SetSkipSwitcher : make the window not appear in a switcher
//
// Setting this bit will indicate that the window prefers not to be listed in a switcher.
//
//	skip: Boolean value that sets whether to skip the window switcher.
func (i *OrgKdePlasmaSurface) SetSkipSwitcher(skip uint32) error {
	const opcode = 9
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(skip))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// OpenUnderCursor : open under cursor
//
// Request the initial position of this surface to be under the current
// cursor position. Has to be called before attaching any buffer to this surface.
func (i *OrgKdePlasmaSurface) OpenUnderCursor() error {
	const opcode = 10
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type OrgKdePlasmaSurfaceRole uint32

// OrgKdePlasmaSurfaceRole :
const (
	OrgKdePlasmaSurfaceRoleNormal                 OrgKdePlasmaSurfaceRole = 0
	OrgKdePlasmaSurfaceRoleDesktop                OrgKdePlasmaSurfaceRole = 1
	OrgKdePlasmaSurfaceRolePanel                  OrgKdePlasmaSurfaceRole = 2
	OrgKdePlasmaSurfaceRoleOnscreendisplay        OrgKdePlasmaSurfaceRole = 3
	OrgKdePlasmaSurfaceRoleNotification           OrgKdePlasmaSurfaceRole = 4
	OrgKdePlasmaSurfaceRoleTooltip                OrgKdePlasmaSurfaceRole = 5
	OrgKdePlasmaSurfaceRoleCriticalnotification   OrgKdePlasmaSurfaceRole = 6
	OrgKdePlasmaSurfaceRoleSystemwindow           OrgKdePlasmaSurfaceRole = 7
	OrgKdePlasmaSurfaceRoleInputpanel             OrgKdePlasmaSurfaceRole = 8
	OrgKdePlasmaSurfaceRoleLogout                 OrgKdePlasmaSurfaceRole = 9
	OrgKdePlasmaSurfaceRoleScreenlock             OrgKdePlasmaSurfaceRole = 10
	OrgKdePlasmaSurfaceRoleScreenlocknotification OrgKdePlasmaSurfaceRole = 11
	OrgKdePlasmaSurfaceRoleWatermark              OrgKdePlasmaSurfaceRole = 12
	OrgKdePlasmaSurfaceRoleAppletpopup            OrgKdePlasmaSurfaceRole = 13
)

func (e OrgKdePlasmaSurfaceRole) Name() string {
	switch e {
	case OrgKdePlasmaSurfaceRoleNormal:
		return "normal"
	case OrgKdePlasmaSurfaceRoleDesktop:
		return "desktop"
	case OrgKdePlasmaSurfaceRolePanel:
		return "panel"
	case OrgKdePlasmaSurfaceRoleOnscreendisplay:
		return "onscreendisplay"
	case OrgKdePlasmaSurfaceRoleNotification:
		return "notification"
	case OrgKdePlasmaSurfaceRoleTooltip:
		return "tooltip"
	case OrgKdePlasmaSurfaceRoleCriticalnotification:
		return "criticalnotification"
	case OrgKdePlasmaSurfaceRoleSystemwindow:
		return "systemwindow"
	case OrgKdePlasmaSurfaceRoleInputpanel:
		return "inputpanel"
	case OrgKdePlasmaSurfaceRoleLogout:
		return "logout"
	case OrgKdePlasmaSurfaceRoleScreenlock:
		return "screenlock"
	case OrgKdePlasmaSurfaceRoleScreenlocknotification:
		return "screenlocknotification"
	case OrgKdePlasmaSurfaceRoleWatermark:
		return "watermark"
	case OrgKdePlasmaSurfaceRoleAppletpopup:
		return "appletpopup"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfaceRole) Value() string {
	switch e {
	case OrgKdePlasmaSurfaceRoleNormal:
		return "0"
	case OrgKdePlasmaSurfaceRoleDesktop:
		return "1"
	case OrgKdePlasmaSurfaceRolePanel:
		return "2"
	case OrgKdePlasmaSurfaceRoleOnscreendisplay:
		return "3"
	case OrgKdePlasmaSurfaceRoleNotification:
		return "4"
	case OrgKdePlasmaSurfaceRoleTooltip:
		return "5"
	case OrgKdePlasmaSurfaceRoleCriticalnotification:
		return "6"
	case OrgKdePlasmaSurfaceRoleSystemwindow:
		return "7"
	case OrgKdePlasmaSurfaceRoleInputpanel:
		return "8"
	case OrgKdePlasmaSurfaceRoleLogout:
		return "9"
	case OrgKdePlasmaSurfaceRoleScreenlock:
		return "10"
	case OrgKdePlasmaSurfaceRoleScreenlocknotification:
		return "11"
	case OrgKdePlasmaSurfaceRoleWatermark:
		return "12"
	case OrgKdePlasmaSurfaceRoleAppletpopup:
		return "13"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfaceRole) String() string {
	return e.Name() + "=" + e.Value()
}

type OrgKdePlasmaSurfacePanelBehavior uint32

// OrgKdePlasmaSurfacePanelBehavior : Behavior for panel surface
const (
	OrgKdePlasmaSurfacePanelBehaviorAlwaysVisible   OrgKdePlasmaSurfacePanelBehavior = 1
	OrgKdePlasmaSurfacePanelBehaviorAutoHide        OrgKdePlasmaSurfacePanelBehavior = 2
	OrgKdePlasmaSurfacePanelBehaviorWindowsCanCover OrgKdePlasmaSurfacePanelBehavior = 3
	OrgKdePlasmaSurfacePanelBehaviorWindowsGoBelow  OrgKdePlasmaSurfacePanelBehavior = 4
)

func (e OrgKdePlasmaSurfacePanelBehavior) Name() string {
	switch e {
	case OrgKdePlasmaSurfacePanelBehaviorAlwaysVisible:
		return "always_visible"
	case OrgKdePlasmaSurfacePanelBehaviorAutoHide:
		return "auto_hide"
	case OrgKdePlasmaSurfacePanelBehaviorWindowsCanCover:
		return "windows_can_cover"
	case OrgKdePlasmaSurfacePanelBehaviorWindowsGoBelow:
		return "windows_go_below"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfacePanelBehavior) Value() string {
	switch e {
	case OrgKdePlasmaSurfacePanelBehaviorAlwaysVisible:
		return "1"
	case OrgKdePlasmaSurfacePanelBehaviorAutoHide:
		return "2"
	case OrgKdePlasmaSurfacePanelBehaviorWindowsCanCover:
		return "3"
	case OrgKdePlasmaSurfacePanelBehaviorWindowsGoBelow:
		return "4"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfacePanelBehavior) String() string {
	return e.Name() + "=" + e.Value()
}

type OrgKdePlasmaSurfaceError uint32

// OrgKdePlasmaSurfaceError :
const (
	// OrgKdePlasmaSurfaceErrorPanelNotAutoHide : Request panel_auto_hide performed on a surface which does not correspond to an auto-hide panel.
	OrgKdePlasmaSurfaceErrorPanelNotAutoHide OrgKdePlasmaSurfaceError = 0
)

func (e OrgKdePlasmaSurfaceError) Name() string {
	switch e {
	case OrgKdePlasmaSurfaceErrorPanelNotAutoHide:
		return "panel_not_auto_hide"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfaceError) Value() string {
	switch e {
	case OrgKdePlasmaSurfaceErrorPanelNotAutoHide:
		return "0"
	default:
		return ""
	}
}

func (e OrgKdePlasmaSurfaceError) String() string {
	return e.Name() + "=" + e.Value()
}

// OrgKdePlasmaSurfaceAutoHiddenPanelHiddenEvent : Auto-hiding panel is hidden
//
// An auto-hiding panel got hidden by the compositor.
type OrgKdePlasmaSurfaceAutoHiddenPanelHiddenEvent struct{}
type OrgKdePlasmaSurfaceAutoHiddenPanelHiddenHandlerFunc func(OrgKdePlasmaSurfaceAutoHiddenPanelHiddenEvent)

// SetAutoHiddenPanelHiddenHandler : sets handler for OrgKdePlasmaSurfaceAutoHiddenPanelHiddenEvent
func (i *OrgKdePlasmaSurface) SetAutoHiddenPanelHiddenHandler(f OrgKdePlasmaSurfaceAutoHiddenPanelHiddenHandlerFunc) {
	i.autoHiddenPanelHiddenHandler = f
}

// OrgKdePlasmaSurfaceAutoHiddenPanelShownEvent : Auto-hiding panel is shown
//
// An auto-hiding panel got shown by the compositor.
type OrgKdePlasmaSurfaceAutoHiddenPanelShownEvent struct{}
type OrgKdePlasmaSurfaceAutoHiddenPanelShownHandlerFunc func(OrgKdePlasmaSurfaceAutoHiddenPanelShownEvent)

// SetAutoHiddenPanelShownHandler : sets handler for OrgKdePlasmaSurfaceAutoHiddenPanelShownEvent
func (i *OrgKdePlasmaSurface) SetAutoHiddenPanelShownHandler(f OrgKdePlasmaSurfaceAutoHiddenPanelShownHandlerFunc) {
	i.autoHiddenPanelShownHandler = f
}

func (i *OrgKdePlasmaSurface) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.autoHiddenPanelHiddenHandler == nil {
			return
		}
		var e OrgKdePlasmaSurfaceAutoHiddenPanelHiddenEvent

		i.autoHiddenPanelHiddenHandler(e)
	case 1:
		if i.autoHiddenPanelShownHandler == nil {
			return
		}
		var e OrgKdePlasmaSurfaceAutoHiddenPanelShownEvent

		i.autoHiddenPanelShownHandler(e)
	}
}
